### ISSUE TITLE
 error: run-p dev styles:watch

### ISSUE THREAD

**Issue by rfikki** [jefflau/ens-manager#14]
c:\projects\ens-manager-master>npm start

> ens-management@0.1.0 start c:\projects\ens-manager-master
> run-p dev styles:watch

'run-p' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Rocky\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ens-management@0.1.0 start: `run-p dev styles:watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ens-management@0.1.0 start script 'run-p dev styles:watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ens-management package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     run-p dev styles:watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ens-management
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ens-management
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Rocky\AppData\Roaming\npm-cache\_logs\2017-06-03T13_08_17_453Z-debug.log

c:\projects\ens-manager-master>

**Comment by jefflau** [comment]
run `npm install`

**Comment by udaykiranravva123** [comment]
npm i npm-run-all 
after installation, you can run-p
