### ISSUE TITLE
subdomain resolver

### ISSUE THREAD

**Issue by bdrehmer** [jefflau/ens-manager#24]
Used https://manager.ens.domains to create a subdomain and set the subdomain to use the default resolver.  Resolver info for subdomain doesn't show up on https://manager.ens.domains even after reloading page etc, but it does show it as being set on etherscan.io.

**Comment by jefflau** [comment]
Were you just setting the resolver? Are you using mist or metamask? Does it still not show up even now? It sounds like it's firing the transactions but it would be weird if wasn't reading it even after a refresh.

**Comment by bdrehmer** [comment]
I used ens-manager to create my subdomain and also to set the default resolver for the subdomain.  I was using metamask with chromium.  This is the etherscan page showing the resolver was set.  https://etherscan.io/enslookup?q=brad.drehmer.eth

**Comment by bdrehmer** [comment]
looks like it has been fixed now.

**Comment by jefflau** [comment]
That's super weird. Thanks for checking that out for me though
