### ISSUE TITLE
delete node: deleting a node results in parent being removed

### ISSUE THREAD

**Issue by obscuren** [jefflau/ens-manager#27]
When creating a sub-sub domain e.g. `sub2.sub1.domain.eth` and deleting it will result in `sub1.domain.eth` to be removed from the UI (not the contract). You can still it back to the list by using the `check for subdomain` feature.

**Comment by jefflau** [comment]
I couldn't replicate your issue, but I realised I had a bug from a refactor on delete. It should be working as expected now. Can you try again and see if it works?

**Comment by jefflau** [comment]
Closing this. Please reopen if you find it is still an issue
