### ISSUE TITLE
default resolver - set address

### ISSUE THREAD

**Issue by bdrehmer** [jefflau/ens-manager#31]
Using default public resolver contract 0x5ffc014343cd971b7eb70732021e26c35b744cc4
After loading my domain and switching to the 'Resolver Details' tab, nothing happens when I put in an address and click 'Set Addr'...no transaction prompt in MetaMask, no feedback in GUI.

**Comment by jefflau** [comment]
Do you get a console error?

**Comment by jefflau** [comment]
This should be fixed in https://github.com/jefflau/ens-manager/commit/77d0b4abce9d81117108b664dbc0b2c472af3e94

Please check for me and close if so.

**Comment by bdrehmer** [comment]
works now, thx!
