### ISSUE TITLE
setSubnodeOwner - transaction failure

### ISSUE THREAD

**Issue by bdrehmer** [jefflau/ens-manager#32]
Transaction to change subdomain owner failed (Bad jump destination)
TxHash: 0x27c067dc8abda60f6dde7b01b366b358b7b64f502eb9fb62a4d632c4d81ffcca
gas used: 4,467,015

Was it out of gas?  It used a lot of gas compared to successful setOwner transaction:
TxHash: 0x2761db9293cdb7caefb8eff20846bb39c2fe3ca90e9aa46c9ec9d60028fa6571
gas used: 31,981

**Comment by jefflau** [comment]
So I asked Nick about this and he said that if the owner isn't your account then it will fail. At one point the ENS manager allowed you to set the owner when you weren't owner (the form would appear). It's possible you may have been on the wrong account? I have updated the app since to only allow owners to use the set forms.

The transaction doesn't say out of gas so I doubt that is the issue

**Comment by bdrehmer** [comment]
Thanks.  I had some confusion about subdomain ownership vs domain ownership.  I first transferred the domain ownership, thinking that it might also transfer ownership of subdomains.  When it didn't, I then tried to transfer the subdomain ownership and ran into this issue.  So you need to transfer subdomain first, then domain?  Still kind of confused.  
Related to this, the gas limit for this tx seems messed up...what it populated for the limit, and subsequently used up when the error occurred, would be the full gas for the block actually, right?

**Comment by bdrehmer** [comment]
I checked it again with the changes that you made and now ENS manager doesn't give me the option of transferring ownership of the subdomain.  The owner of the subdomain is the MetaMask address that I'm connected with though, so that's pretty confusing.  I guess I'd be able to transfer the subdomain ownership if I accessed ENS manager via the address that I transferred to domain ownership to, and to avoid this problem I should have transferred the subdomain ownership **before** transferring the domain ownership.  Any ideas on how to make this all more intuitive?

**Comment by jefflau** [comment]
If the owner is the account you're connected with, you should 100% be able to change the owner. If you can't change the owner, but you are the owner as well, then that definitely is a bug.

The difference between setSubnodeOwner and setOwner is that the former allows you to set the owner of children nodes of the parent you own. The latter only allows you to change the owner of the node you are on. Both functions will actually work if you are the owner of the node as well as the parent node.

**Comment by jefflau** [comment]
I just checked on mist and I couldn't replicate what you mentioned. I will try and transfer the owner of the node and check on metamask too

**Comment by bdrehmer** [comment]
I created the subdomain using the same MetaMask account, so it is definitely the right account that owns the subdomain.
I just refreshed again and this time it does have all of the owner functionality for the subdomain, so maybe it will work.  The MetaMask prompt has gas limit '6352237' though, which is I guess a separate issue.  Anyway, I'm going to try the transfer again.  Do you know how much gas it should take?

**Comment by jefflau** [comment]
I'm not sure how much gas it should take off the top of my head. @Arachnid should probably be able to give you a better answer.

**Comment by bdrehmer** [comment]
I tried with 100000 gas limit. 
Tx failed again:
https://etherscan.io/tx/0xe9a556f10adb2665ee8e67aefd34c98e57b4f79f5e769c3aec3f01dac6c1171a

domain: https://etherscan.io/enslookup?q=drehmer.eth
subdomain: https://etherscan.io/enslookup?q=brad.drehmer.eth

**Comment by jefflau** [comment]
I think I have an idea what's going on. Let me do some digging

**Comment by jefflau** [comment]
I've pushed a fix. I think the problem was it was calling 'setSubnodeOwner' when it should have been calling 'setOwner', because the node's owner is not the parent's owner and so it can't make that call. Can you see if that works?

**Comment by bdrehmer** [comment]
pending...
https://etherscan.io/tx/0x1350ff423256d3082d9a1635db55a71c7d2c396fd75c6edd8dfa2d9f3f38248a

**Comment by bdrehmer** [comment]
it worked now :+1: 
please check gas limit for setSubnodeOwner if that is still called anywhere

**Comment by jefflau** [comment]
I did a call earlier  to setSubnodeOwner on testnet and it cost around 130000 gas.

https://ropsten.etherscan.io/tx/0x4e41f7c49d815c78491fa0a155736d36f8eff91ea5209015b260a5aea1ca0c4d

**Comment by Arachnid** [comment]
That call on ropsten cost 34713, not 130k.
