### ISSUE TITLE
not recognizing me as domain owner

### ISSUE THREAD

**Issue by bdrehmer** [jefflau/ens-manager#37]
I'm using Mist 0.9.0 with Ledger Nano S and authorized the account that owns the domain.  I'm trying to play with the Swarm integration and set the content of my resolver, but none of the buttons are showing up that allow me to manage the domain.  I see in the dev console that it thinks it is using MetaMask when the page loads?  Maybe it is broken with latest release of Mist?

**Comment by jefflau** [comment]
That's weird that it thinks its metamask, if you're using Mist. Current version of the manager will break in Mist 0.9.0 as described in https://github.com/jefflau/ens-manager/issues/36

Working on a fix now. Will keep you updated

**Comment by jefflau** [comment]
I've pushed a fix and deployed. Can you let me know if you still have this issue?

**Comment by bdrehmer** [comment]
works now, thx!
