### ISSUE TITLE
Sending ens name to invalid address

### ISSUE THREAD

**Issue by wuno** [jefflau/ens-manager#43]

**Comment by jefflau** [comment]
Hi @wuno,

I saw you closed this, but I still saw the message on my email. I'm wondering what happened regardless

**Comment by wuno** [comment]
I was trying to delete it. I really wish I would of left it up. Would you mind sending me the copy from your email so I can edit the initial post I made by adding it back? That way people can learn from this idiot thing I did.

**What Happened**

At first the form was submitted blank. After a few minutes when checking the ens name again, the address mentioned before was attached to it. I wanted to know why so I cloned the repo and found this function,

```
function getNamehash(name) {
  return getWeb3().then(({ web3 }) =>{
    var node = '0x0000000000000000000000000000000000000000000000000000000000000000';
    if (name !== '') {
        var labels = name.split(".");
        for(var i = labels.length - 1; i >= 0; i--) {
            node = web3.sha3(node + web3.sha3(labels[i]).slice(2), {encoding: 'hex'});
        }
    }
    return node.toString();
  })
}

```

I assume when it was blank, it used this address for whatever reason in the code.

I kept checking and could not find the ens name attached to that account though. So after an hour, I started looking other places. I found this place to manage the ens https://enslisting.com/manage/home

I noticed that here it showed the ens name attached to my public address again after 1 hour. At this point, I was able to follow the automated steps at that URL and completed setting up the ens so it was mapped to my public ether address.

So in the end it was somehow attached to my public address again. I was super lucky on this one... I would love to know how it bounced back though. When I checked the history of the ens I did not see it ever being set to this, 

> 0x0000000000000000000000000000000000000000000000000000000000000000
