### ISSUE TITLE
[Minor] Add correct subdomain prefix for etherescan links

### ISSUE THREAD

**Issue by jopasserat** [jefflau/ens-manager#51]
Just a minor UX tweak: when browsing the records for a given name (ex: https://manager.ens.domains/name/michalzalecki.test), it would be nice to have the links pointing to the right Etherscan subdomain according to the current account in the injected web3.

For instance, when browsing [this name](https://manager.ens.domains/name/michalzalecki.test), registered in rinkeby, the owner, resolver and address links all point to the mainnet's version of Etherscan.

[Main net Owner => "no matching entries"](http://etherscan.io/address/0x7D20cb28C496A76173eE828ecacfB08dEB379E8d)
[Rinkeby Owner => success](http://rinkeby.etherscan.io/address/0x7D20cb28C496A76173eE828ecacfB08dEB379E8d)

**Comment by jefflau** [comment]
Thanks for this issue. Could you please move it to the new repo, this is for the original manager which was deprecated last year December. Thanks!

https://github.com/ensdomains/ens-app

**Comment by jopasserat** [comment]
reopened in [new repo](https://github.com/ensdomains/ens-app/issues/108)
